---
title: "labSession3"
author: "Maé-Li Gendron"
date: "9/15/2017"
output: html_document
---

```{r}
# Loading the gsheet library
library(gsheet)

# Using the gsheet2tbl function to import data related to cluster from different fields into the RStudio console
dataCluster <- gsheet2tbl("https://docs.google.com/spreadsheets/d/14nK3iAFdHkb7lW-9ZVFDj2xxpDolOjKJTiOZG7Zhxg8/edit?usp=sharing")

# Add a new column called 'newColumn'
dataCluster$newColumn <- 42

# Multiply by 2 and add 5
dataCluster$newColumn <- dataCluster$newColumn * 2 + 5

# Delete the column named 'newColumn'
dataCluster$newColumn <- NULL

# First 6 lines of the dataset
head(dataCluster)
```

```{r}
# Transformation from character to numerical values
dataCluster$country <- sapply(dataCluster$country, as.factor)
dataCluster$year <- sapply(dataCluster$year, as.numeric)
dataCluster$cluster <- sapply(dataCluster$cluster, as.factor)
dataCluster$nbEstablishments <- sapply(dataCluster$nbEstablishments, as.numeric)
dataCluster$employment <- sapply(dataCluster$employment, as.numeric)
dataCluster$wages <- sapply(dataCluster$wages, as.numeric)

# First 6 lines of the dataset
summary(dataCluster)
```


```{r}
# Loading the gsheet library
library(gsheet)

# Using the gsheet2tbl function to import data related to cluster from different fields into the RStudio console
dataCluster <- gsheet2tbl("https://docs.google.com/spreadsheets/d/14nK3iAFdHkb7lW-9ZVFDj2xxpDolOjKJTiOZG7Zhxg8/edit?usp=sharing")

head(dataClusterSubset)

# Merging 2 datasets
newData <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1OlMs0uwaDI4AI0gprDYckPpsFaL5k38sULytKHnFZMY/edit?usp=sharing")

dataMerged <- bind_rows(dataCluster, newData)

# loading the new dataset
patentsClaims <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1h04vYRmhxj4fRhe79dJ0h4e9l2lBbNLkNyaxiSdS5lE/edit?usp=sharing")

# Merging 2 datasets
dataFull <- full_join(dataMerged, patentsClaims, c("country","year","cluster"))
```
```{r}
# Loading the gsheet library
library(gsheet)

# Using the gsheet2tbl function to import data related to cluster from different fields into the RStudio console
dataCluster <- gsheet2tbl("https://docs.google.com/spreadsheets/d/14nK3iAFdHkb7lW-9ZVFDj2xxpDolOjKJTiOZG7Zhxg8/edit?usp=sharing")

# Merging 2 datasets
newData <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1OlMs0uwaDI4AI0gprDYckPpsFaL5k38sULytKHnFZMY/edit?usp=sharing")

dataMerged <- bind_rows(dataCluster, newData)

# loading the new dataset
patentsClaims <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1h04vYRmhxj4fRhe79dJ0h4e9l2lBbNLkNyaxiSdS5lE/edit?usp=sharing")

# Merging 2 datasets
dataFull <- full_join(dataMerged, patentsClaims, c("country","year","cluster"))

```

```{r}
# Produce a bar chart concerning the number of establishments
library(ggplot2)
library(ggthemes)
ggplot(data = dataFull, aes(x = year, y = nbEstablishments, fill = cluster)) + 
  geom_bar(stat = "identity", width = 0.5, position = "dodge")  +  
  ylab("Number of establishments")  +
  xlab("") +
  guides(col = guide_legend(row = 1)) +
  theme_hc()
```

```{r}
# Produce a bar chart concerning the number of employees
library(ggplot2)
library(ggthemes)
ggplot(data = dataFull, aes(x = year, y = employment, fill = cluster)) + 
  geom_bar(stat = "identity", width = 0.5, position = "dodge")  +  
  ylab("Number of employees")  +
  xlab("") +
  guides(col = guide_legend(row = 1)) +
  theme_hc()
```

